### ISSUE TITLE
Register/Add replicas based on UUIDs instead of IP Addresses

### ISSUE THREAD

**Issue by ksatchit** [openebs/longhorn#17]
<to be filled>

**Comment by ksatchit** [comment]
cc: @utkarshmani1997

**Comment by kmjayadeep** [comment]
i would like to give a try for this

**Comment by utkarshmani1997** [comment]
@kmjayadeep thanks for showing interest in this. Just let us know if you need any help.

**Comment by kmjayadeep** [comment]
What about the files you mentioned? you said you'll share with me

**Comment by utkarshmani1997** [comment]
@kmjayadeep check your slack handle.

**Comment by khushbuparakh** [comment]
@utkarshmani1997  is it being done?. Else if you can share the files on this issue as well.

**Comment by utkarshmani1997** [comment]
Hi @khushbuparakh thanks for showing interest @kmjayadeep is already working on it. You may check for other issues opened [here](https://github.com/openebs/longhorn/issues) or at [openebs/openebs/issues](https://github.com/openebs/openebs/issues)
