### ISSUE TITLE
Speed up the replica sync process

### ISSUE THREAD

**Issue by ksatchit** [openebs/longhorn#18]
Currently, in longhorn, when replica connects to controller, replica gets its data synced from other healthy RW replica. Healthy replica reads the entire data to find the snapshot that need to be rebuilt at WO replica. This is time taking process. This US is to speed up the sync process between RW and WO replicas.

**Comment by ksatchit** [comment]
cc: @payes

**Comment by khushbuparakh** [comment]
Do you have any design flow in mind to speed up this process of sync the data @ksatchit?.

**Comment by vishnuitta** [comment]
@khushbuparakh 
When this issue was created, idea was to have IOSeq stored per snapshot when snapshot gets created. This way, we should be able to avoid verifying for entire data in all snapshots.
This issue is open for new thoughts as well.
Thanks for showing interest in this issue.

**Comment by vishnuitta** [comment]
@payes ^^^

**Comment by devjyotipatra** [comment]
@vishnuitta  @payes  If this is upforgrabs, i would like to take this up.
