### ISSUE TITLE
Avoid 'defer unlocks' in hot paths of longhorn

### ISSUE THREAD

**Issue by ksatchit** [openebs/longhorn#24]
There seems to be heavy overhead with usage of 'defer unlocks' in go code. This link says so: https://medium.com/i0exception/runtime-overhead-of-using-defer-in-go-7140d5c40e32

This issue is to convert 'defer unlocks' to just unlocks at all the required exit places in hot paths of longhorn.

**Comment by ksatchit** [comment]
cc: @payes @vishnuitta

**Comment by klebervirgilio** [comment]
Hi, if I got it correctly, we're talking about replacing: `defer mu.Unlock()` to just calling `mu.Unlock()` in the end of the function?

**Comment by utkarshmani1997** [comment]
@klebervirgilio you are correct. This has to be handled optimally

**Comment by klebervirgilio** [comment]
Got it! Thanks @umamukkara 

1. Which are the `hot paths`? 
2. How can I start on this one and how would I know I'd have finished?

**Comment by vishnuitta** [comment]
@klebervirgilio .. thanks for showing interest in this
Hot paths are related to IO paths.
You can start from ReadAt, WriteAt functions in controller/control.go and follow the path to know IO path in controller side, and,
similarly Handle() in rpc/server.go for replica side IO handling.

**Comment by khushbuparakh** [comment]
@vishnuitta  @klebervirgilio  If it's still up for grab. I would like to work on it?

**Comment by utkarshmani1997** [comment]
Hi @khushbuparakh , Thanks for showing interest in this. Please go ahead and let us know if you need any help.

Happy Hacktoberfest :)
