### ISSUE TITLE
Integration tests are failing. 

### ISSUE THREAD

**Issue by kmova** [openebs/longhorn#4]
To get the test image, temporarily skipping the integration tests

**Comment by ajkumar01** [comment]
Its working now, we can re-enable integration test

It was a temporary failure - in ssl connection!
Can see lots of references to this type of temporary failures in 'google search'.

When it was failing, this was the error:
"Could not fetch URL https://pypi.python.org/simple/cattle/: There was a problem confirming the ssl certificate: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1754) - skipping"

**Comment by ajkumar01** [comment]
For faster build process do:
    make build           -- just compiles the code
and
   make package     -- just creates the longhorn container image

**Comment by ajkumar01** [comment]
Also, there is no need to do  'sudo make'
We need to add the current 'user' to the 'docker' group.

sudo groupadd docker; 
sudo usermod -aG docker $USER  (assuming the current shell is in the user we want to compile with)

**Comment by kmova** [comment]
@ajkumar01 the make fails with the following error when run from within the virtual box using the steps listed here ( https://github.com/openebs/elves ). 

Built openebs/longhorn:d52af8e-dirty
INFO[0063] docker cp /go/src/github.com/openebs/longhorn/bin . 
chmod /opt/gopath/src/github.com/openebs/longhorn/bin: operation not permitted

Also, docker user is already added:
vagrant@openebs-dev-01:/opt/gopath/src/github.com/openebs/longhorn$ sudo groupadd docker
groupadd: group 'docker' already exists

We can close this issue when the make succeeds by following the instructions listed in:
https://github.com/openebs/elves
